### ISSUE TITLE
Remove color red from background behind banner photo

### ISSUE THREAD

**Issue by terminallysilly** [terminallysilly/terminallysilly.github.io#3]
If banner photo takes a second to load (e.g. due to slow network connection, etc.), the background color behind the space where the image loads is bright red, which is out of keeping with the site color schema. This appears to be a holdover from the original Hugo template that was used as a skeleton for the site build.

**Comment by terminallysilly** [comment]
Adding "bug" label because I tried changing the hex codes for colors throughout the repo to make sure the red hex `#b80135` wasn't present; works locally but not in prod @LivInAbsurdism

**Comment by LivInAbsurdism** [comment]
@terminallysilly we might need to make changes to [the other repo](https://github.com/terminallysilly/hugo_scroll_custom) that the scroll theme is coming from. We forked it early on in case this happened, but it's possible the color is originating from there. 

I'll go check that out.

**Comment by LivInAbsurdism** [comment]
Huzzah! We have success. I was able to change the hex codes in the theme repo we forked and then update the submodules in this repo. Change is reflecting in prod. @terminallysilly will you close this issue?

**Comment by terminallysilly** [comment]
Issue resolved
